# Generated by Django 3.2.5 on 2023-08-11 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resturant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rname', models.CharField(max_length=200)),
                ('remail', models.CharField(max_length=20)),
                ('rmobileNumber', models.CharField(max_length=12)),
                ('rusername', models.CharField(max_length=20)),
                ('rpassword', models.CharField(max_length=20)),
                ('raddress', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='address',
            new_name='caddress',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='age',
            new_name='cage',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='email',
            new_name='cemail',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='mobileNumber',
            new_name='cmobileNumber',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='cname',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='password',
            new_name='cpassword',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='username',
            new_name='cusername',
        ),
    ]
