# Generated by Django 3.2.5 on 2023-08-11 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0002_auto_20230811_1152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='caddress',
            new_name='c_address',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='cage',
            new_name='c_age',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='cemail',
            new_name='c_email',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='cmobileNumber',
            new_name='c_mobileNumber',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='cname',
            new_name='c_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='cpassword',
            new_name='c_password',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='cusername',
            new_name='c_username',
        ),
        migrations.RenameField(
            model_name='resturant',
            old_name='raddress',
            new_name='r_address',
        ),
        migrations.RenameField(
            model_name='resturant',
            old_name='remail',
            new_name='r_email',
        ),
        migrations.RenameField(
            model_name='resturant',
            old_name='rmobileNumber',
            new_name='r_mobileNumber',
        ),
        migrations.RenameField(
            model_name='resturant',
            old_name='rname',
            new_name='r_name',
        ),
        migrations.RenameField(
            model_name='resturant',
            old_name='rpassword',
            new_name='r_password',
        ),
        migrations.RenameField(
            model_name='resturant',
            old_name='rusername',
            new_name='r_username',
        ),
    ]
