# Generated by Django 3.2.5 on 2023-09-13 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0003_auto_20230811_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers_complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=200)),
                ('c_username', models.CharField(max_length=20)),
                ('c_email', models.CharField(max_length=20)),
                ('c_complaint', models.CharField(max_length=200)),
            ],
        ),
    ]
