# Generated by Django 3.2.5 on 2023-09-23 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0004_customers_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='fooditem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_id', models.CharField(max_length=20)),
                ('food_name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=10)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
