# Generated by Django 3.2.5 on 2024-01-31 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0007_remove_customer_c_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_username', models.CharField(max_length=20)),
                ('a_name', models.CharField(max_length=200)),
                ('a_email', models.CharField(max_length=20)),
                ('a_password', models.CharField(max_length=20)),
            ],
        ),
    ]
