# Generated by Django 3.2.5 on 2024-01-31 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0008_admin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='admin',
            new_name='admin_data',
        ),
    ]
