# Generated by Django 3.2.5 on 2024-02-01 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0009_rename_admin_admin_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resturant_staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rs_username', models.CharField(max_length=20)),
                ('rs_name', models.CharField(max_length=200)),
                ('rs_email', models.CharField(max_length=20)),
                ('rs_mobileNumber', models.CharField(max_length=12)),
                ('rs_password', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Resturant',
        ),
    ]
