# Generated by Django 4.2.4 on 2024-02-21 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0010_auto_20240201_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('stock', models.IntegerField()),
                ('username', models.CharField(max_length=20)),
                ('user_email', models.CharField(max_length=20)),
            ],
        ),
    ]
