# Generated by Django 4.2.4 on 2024-02-21 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0011_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='stock',
            new_name='quantity',
        ),
    ]
