# Generated by Django 4.2.4 on 2024-04-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0013_completedorder_ongoingorder_order_remove_cart_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='userEmail',
            field=models.EmailField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='username',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
