# Generated by Django 4.2.4 on 2024-04-04 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0014_cart_useremail_cart_username_alter_cart_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('username', models.CharField(max_length=20)),
            ],
        ),
    ]
