# Generated by Django 4.2.4 on 2024-04-04 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0015_pay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pay',
            name='username',
        ),
        migrations.AddField(
            model_name='cart',
            name='c_mobileNumber',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='completedorder',
            name='phnumber',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pay',
            name='c_mobileNumber',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
